### ISSUE TITLE
Scalling tilemaps

### ISSUE THREAD

**Issue by Mierzmit** [mini2Dx/mini2Dx#50]
I want use g.scale in order to makes tilemap looking exacly the same on different resolutions.
After I set scale tilemap is not rendered fully.
I think there should be option to include graphics scale in draw tilemap calculations.

**Comment by tomcashman** [comment]
Have you enabled the cacheLayers options on the TiledMap?

**Comment by Mierzmit** [comment]
When I enabled cacheLayers it gives exception:
```
Exception in thread "LWJGL Application" java.nio.BufferOverflowException
	at java.nio.DirectFloatBufferU.put(Unknown Source)
	at com.badlogic.gdx.graphics.g2d.SpriteCache.add(SpriteCache.java:259)
	at com.badlogic.gdx.graphics.g2d.SpriteCache.add(SpriteCache.java:678)
	at com.badlogic.gdx.graphics.g2d.SpriteCache.add(SpriteCache.java:642)
	at org.mini2Dx.tiled.renderer.OrthogonalTileLayerRenderer.renderLayerToCache(OrthogonalTileLayerRenderer.java:168)
	at org.mini2Dx.tiled.renderer.OrthogonalTileLayerRenderer.renderCachedLayer(OrthogonalTileLayerRenderer.java:102)
	at org.mini2Dx.tiled.renderer.OrthogonalTileLayerRenderer.drawLayer(OrthogonalTileLayerRenderer.java:77)
	at org.mini2Dx.tiled.TiledMap.drawLayer(TiledMap.java:317)
	at org.mini2Dx.tiled.TiledMap.draw(TiledMap.java:254)
	at org.mini2Dx.tiled.TiledMap.draw(TiledMap.java:226)
	at org.mini2Dx.tiled.TiledMap.draw(TiledMap.java:186)
	at com.airstrike.main.PlayState.render(PlayState.java:74)
```

**Comment by tomcashman** [comment]
The TiledMap should scale without enabling cacheLayers. If you run the Tiled UATs in the mini2Dx UAT project you'll see it working. I also used the scaling in Bard to the Future.

So I'm not sure why it's not working for you :/

**Comment by Mierzmit** [comment]
![scale](https://cloud.githubusercontent.com/assets/13609541/12217122/de655e00-b6f6-11e5-9451-24ed03027989.png)
800x480 is my 'native' resolution.
When I up-scaling everything works well but down-scaling under 800x480 cause map not fully rendered.
I will take look on mini2Dx UAT project later.

**Comment by tomcashman** [comment]
Ah so the problem is with downscaling, not upscaling. Okay I will investigate.
