### ISSUE TITLE
UnsatisfiedLinkError when running project generator

### ISSUE THREAD

**Issue by sonirico** [mini2Dx/mini2Dx#60]
I have downloaded the [latest version project generator for Linux](http://mini2dx.org/downloads/mini2Dx-project-generator-linux.zip) and tried to run the bash file with no successful results. Output displayed:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/[censored]/Projects/mini2Dx-project-generator-linux/jre/lib/i386/xawt/libmawt.so: libXext.so.6: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1872)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1653)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1682)
	at java.awt.Component.<clinit>(Component.java:595)

Then, I checked that the problem, at least partially, has to do with the java executable file. Instead of using the "$APPLICATION_HOME/jre/bin/java" one -which is supposed to be run ever, since $INCLUDE_JRE is set to TRUE an its value never changes- I used the native java OpenJDK 1.7.0_101 version of by OS. The project generator turned out to work this time, running the following command:

` java -Xmx512m -classpath /home/[censored]/Projects/mini2Dx-project-generator-linux/libs/mini2Dx-project-generator-1.1.0.jar:/home/[censored]/Projects/mini2Dx-project-generator-linux/libs/java-semver-0.9.0.jar com.badlogic.gdx.setup.GdxSetupUI 
`

with the following output, just in case:

> project-generator-linux/libs/java-semver-0.9.0.jar com.badlogic.gdx.setup.GdxSetupUI 
Project Generator Version: 1.1.0
Required Project Generator Version: 1.1.0
Found Release [libGDX: 1.6.5][mini2Dx: 1.2.1][parcl: 1.0.6][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.6.0][deprecated: false]
Found Release [libGDX: 1.6.5][mini2Dx: 1.2.0][parcl: 1.0.6][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.6.0][deprecated: false]
Ignoring deprecated release: Release [libGDX: 1.6.4][mini2Dx: 1.1.0][parcl: 1.0.6][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.5.0][deprecated: true]
Ignoring deprecated release: Release [libGDX: 1.6.1][mini2Dx: 1.0.1][parcl: 1.0.6][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.2.0][deprecated: true]
Ignoring deprecated release: Release [libGDX: 1.6.1][mini2Dx: 1.0.0][parcl: 1.0.6][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.2.0][deprecated: true]
Ignoring deprecated release: Release [libGDX: 1.6.1][mini2Dx: 1.0.0-RC2][parcl: 1.0.6][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.2.0][deprecated: true]
Ignoring deprecated release: Release [libGDX: 1.6.1][mini2Dx: 1.0.0-RC1][parcl: 1.0.5][androidApi: 20][androidBuildTools: 20.0.0][roboVM: 1.2.0][deprecated: true]

Any ideas? Might the bash script be wrong?

**Comment by tomcashman** [comment]
Thanks for reporting the issue!

Can I ask what OS you are using?

**Comment by sonirico** [comment]
Sure! I
`> uname -a
Linux localhost 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux

`
